# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none


variables:
- group: niraj_vg

parameters:
  - name: Testing
    displayName: Testing attributes
    type: string
    values:
    - ABC
    - DEF
    default: ABC
  - name: SelfHostedAgentName
    displayName: Agent Pool Machines
    type: string
    default: agent8
    values:
    - agent8
    - agent10
    - agent7

jobs:
 - job: Test

   pool: 
     name: niraj_agent
     demands: 
       - Agent.Name -equals ${{ parameters.SelfHostedAgentName }}
   cancelTimeoutInMinutes: 10 
   timeoutInMinutes: 15 
   steps:
    - script: echo Hello, world! 
      displayName: 'Run a one-line script'


    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here      
          pwd
          echo "AFter PWD"
          ls -l
          sleep 10m
          echo Add other tasks to build, test, and deploy your project.
          echo "See https://aka.ms/yaml"
      enabled: true