# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
- group: niraj_vg

parameters:
  - name: Testing
    displayName: Testing attributes
    type: string
    values:
    - ABC
    - DEF
    default: ABC

jobs:
 - job: Test

   pool: niraj_agent

   steps:
    - script: echo Hello, world! 
      displayName: 'Run a one-line script'

    - script: |
       bash test.sh
       echo Add other tasks to build, test, and deploy your project.
       echo See https://aka.ms/yaml
