# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none


variables:
- group: niraj_vg

parameters:
  - name: Testing
    displayName: Testing attributes
    type: string
    values:
    - ABC
    - DEF
    default: ABC
  - name: SelfHostedAgentName
    displayName: Agent Pool Machines
    type: string
    default: agent6
    values:
    - agent5
    - agent6
    - agent7

jobs:
 - job: Test

   pool: 
     name: niraj_agent
     demands: ${{ parameters.SelfHostedAgentName }}
   
   steps:
    - script: echo Hello, world! 
      displayName: 'Run a one-line script'

    - script: |
       pwd
       echo "AFter PWD"
       ll
       echo Add other tasks to build, test, and deploy your project.
       echo See https://aka.ms/yaml
